In [1]:
import pandas as pd
import numpy as np
from rdkit.Chem import Descriptors, Draw
from rdkit import Chem
import json

In [2]:
allowed_descriptors = pd.read_json('all_peptide_descriptors.json')
allowed_descriptors = allowed_descriptors.iloc[:, 0].tolist()
allowed_descriptors

['peoe_vsa2',
 'ringcount',
 'kappa3',
 'fr_nh2',
 'estate_vsa10',
 'slogp_vsa3',
 'numheteroatoms',
 'nhohcount',
 'numhdonors',
 'peoe_vsa14',
 'numhacceptors',
 'bcut2d_logplow',
 'minabsestateindex',
 'peoe_vsa6',
 'bcut2d_chglo',
 'hallkieralpha',
 'smr_vsa1',
 'smr_vsa7',
 'chi3n',
 'minabspartialcharge',
 'numsaturatedheterocycles',
 'fpdensitymorgan3',
 'estate_vsa2',
 'kappa1',
 'fr_guanido',
 'nocount',
 'estate_vsa8',
 'minpartialcharge',
 'bcut2d_mrlow',
 'fr_unbrch_alkane',
 'chi0v',
 'slogp_vsa5',
 'estate_vsa7',
 'vsa_estate5',
 'estate_vsa11',
 'qed',
 'smr_vsa6',
 'numaromaticcarbocycles',
 'maxabspartialcharge',
 'minestateindex',
 'estate_vsa9',
 'estate_vsa3',
 'molmr',
 'chi0',
 'estate_vsa6',
 'fpdensitymorgan2',
 'smr_vsa4',
 'bertzct',
 'maxpartialcharge',
 'vsa_estate2',
 'vsa_estate8',
 'bcut2d_logphi',
 'numvalenceelectrons',
 'estate_vsa4',
 'estate_vsa5',
 'heavyatommolwt',
 'fr_benzene',
 'peoe_vsa9',
 'vsa_estate4',
 'slogp_vsa4',
 'slogp_vsa2',
 'fr_c_o_nocoo',
 'bcut2d_mwlow',
 'fr_nh1',
 'smr_vsa10',
 'smr_vsa5',
 'heavyatomcount',
 'fr_nh0',
 'vsa_estate7',
 'chi2v',
 'fpdensitymorgan1',
 'bcut2d_mwhi',
 'smr_vsa3',
 'slogp_vsa6',
 'peoe_vsa12',
 'peoe_vsa7',
 'tpsa',
 'numaromaticheterocycles',
 'fractioncsp3',
 'molwt',
 'fr_ar_n',
 'vsa_estate3',
 'numsaturatedrings',
 'fr_para_hydroxylation',
 'peoe_vsa10',
 'maxestateindex',
 'balabanj',
 'numrotatablebonds',
 'mollogp',
 'slogp_vsa1',
 'peoe_vsa1',
 'fr_amide',
 'peoe_vsa8',
 'bcut2d_chghi',
 'chi1v',
 'fr_c_o',
 'chi0n',
 'labuteasa',
 'fr_imidazole',
 'numaliphaticrings',
 'chi4n',
 'chi1',
 'vsa_estate6',
 'peoe_vsa3',
 'exactmolwt',
 'bcut2d_mrhi',
 'estate_vsa1',
 'chi4v',
 'chi3v',
 'chi1n',
 'chi2n',
 'numaliphaticheterocycles',
 'numaromaticrings',
 'kappa2',
 'maxabsestateindex']

## Nodes: Format Data & Get Features

In [3]:
peptide_nodes = pd.read_csv("../tables/SMILES_peptides_monomer.txt")
peptide_nodes['class'] = peptide_nodes.apply(lambda row: 'peptide_amd' if '_amd' in row['Molecule'] else 'peptide', axis=1)
peptide_nodes['type'] = 'node'

peptide_edges = pd.read_csv("../tables/SMILES_peptides_bond.txt")
peptide_edges['class'] = 'peptide'
peptide_edges['type'] = 'edge'

polymer_nodes = pd.read_csv("../tables_poly/SMILES_polymers_monomer.txt")
polymer_nodes['class'] = 'polymer'
polymer_nodes['type'] = 'node'

polymer_edges = pd.read_csv("../tables_poly/SMILES_polymers_bond.txt")
polymer_edges['class'] = 'polymer'
polymer_edges['type'] = 'edge'

df = pd.concat([peptide_nodes, polymer_nodes, peptide_edges, polymer_edges], ignore_index = True)
df = df.rename(columns = {'Molecule': 'monomer'})
df = df.drop(['Description'], axis=1)

In [4]:
df

   monomer                                 SMILES        class  type
0        G                             C(C(=O)O)N      peptide  node
1        A                       C[C@@H](C(=O)O)N      peptide  node
2        L                  CC(C)C[C@@H](C(=O)O)N      peptide  node
3        M                    CSCC[C@@H](C(=O)O)N      peptide  node
4        F          C1=CC=C(C=C1)C[C@@H](C(=O)O)N      peptide  node
5        W  C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N      peptide  node
6        K                 C(CCN)C[C@@H](C(=O)O)N      peptide  node
7        Q              C(CC(=O)N)[C@@H](C(=O)O)N      peptide  node
8        E              C(CC(=O)O)[C@@H](C(=O)O)N      peptide  node
9        S                    C([C@@H](C(=O)O)N)O      peptide  node
10       P                    C1C[C@H](NC1)C(=O)O      peptide  node
11       V                   CC(C)[C@@H](C(=O)O)N      peptide  node
12       I              CC[C@H](C)[C@@H](C(=O)O)N      peptide  node
13       C                    C([C@@H](C(=O)O)N)S      peptide  node
14       Y         C1=CC(=CC=C1C[C@@H](C(=O)O)N)O      peptide  node
15       H            C1=C(NC=N1)C[C@@H](C(=O)O)N      peptide  node
16       R            C(C[C@@H](C(=O)O)N)CN=C(N)N      peptide  node
17       N               C([C@@H](C(=O)O)N)C(=O)N      peptide  node
18       D               C([C@@H](C(=O)O)N)C(=O)O      peptide  node
19       T               C[C@H]([C@@H](C(=O)O)N)O      peptide  node
20   G_amd                             C(C(=O)N)N  peptide_amd  node
21   A_amd                       C[C@@H](C(=O)N)N  peptide_amd  node
22   L_amd                  CC(C)C[C@@H](C(=O)N)N  peptide_amd  node
23   M_amd                    CSCC[C@@H](C(=O)N)N  peptide_amd  node
24   F_amd          C1=CC=C(C=C1)C[C@@H](C(=O)N)N  peptide_amd  node
25   W_amd  C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)N)N  peptide_amd  node
26   K_amd                 C(CCN)C[C@@H](C(=O)N)N  peptide_amd  node
27   Q_amd              C(CC(=O)N)[C@@H](C(=O)N)N  peptide_amd  node
28   E_amd              C(CC(=O)O)[C@@H](C(=O)N)N  peptide_amd  node
29   S_amd                    C([C@@H](C(=O)N)N)O  peptide_amd  node
30   P_amd                    C1C[C@H](NC1)C(=O)N  peptide_amd  node
31   V_amd                   CC(C)[C@@H](C(=O)N)N  peptide_amd  node
32   I_amd              CC[C@H](C)[C@@H](C(=O)N)N  peptide_amd  node
33   C_amd                    C([C@@H](C(=O)N)N)S  peptide_amd  node
34   Y_amd         C1=CC(=CC=C1C[C@@H](C(=O)N)N)O  peptide_amd  node
35   H_amd            C1=C(NC=N1)C[C@@H](C(=O)N)N  peptide_amd  node
36   R_amd            C(C[C@@H](C(=O)N)N)CN=C(N)N  peptide_amd  node
37   N_amd               C([C@@H](C(=O)N)N)C(=O)N  peptide_amd  node
38   D_amd               C([C@@H](C(=O)N)N)C(=O)O  peptide_amd  node
39   T_amd               C[C@H]([C@@H](C(=O)N)N)O  peptide_amd  node
40     Tma                C[N+](C)(C)CCCNC(=O)C=C      polymer  node
41     Aeg                NC(=[NH2+])NCCNC(=O)C=C      polymer  node
42      Mo                       C=CC(=O)N1CCOCC1      polymer  node
43     Mep                         COCCCNC(=O)C=C      polymer  node
44      Ni                         CC(C)NC(=O)C=C      polymer  node
45     Phe                      C=CC(=O)Nc1ccccc1      polymer  node
46      Do                  CCCCCCCCCCCCNC(=O)C=C      polymer  node
47     Bam                          CCCCNC(=O)C=C      polymer  node
48     Oct                      CCCCCCCCNC(=O)C=C      polymer  node
49    Olam       CCCCCCCC/C=C\CCCCCCCCNC(=O)C(=C)      polymer  node
50    Bmam                        CCCCOCNC(=O)C=C      polymer  node
51     Tmb              CC(C)(C)CC(C)(C)NC(=O)C=C      polymer  node
52     AMB                               CNC(C)=O      peptide  edge
53      CC                                     CC      polymer  edge

In [5]:
%%capture
df['descriptors'] = df['SMILES'].apply(
    lambda x: Descriptors.CalcMolDescriptors(
        Chem.MolFromSmiles(x), missingVal=-9999, silent=True
    )
)

df['descriptors'] = df['descriptors'].apply(
    lambda descriptor_dict: {
        key: value for key, value in descriptor_dict.items() 
        if key.lower() in allowed_descriptors
    }
)

expanded_df = pd.json_normalize(df['descriptors'])
expanded_df.index = df.index
df = df.drop(columns=['descriptors'])
df = pd.concat([df, expanded_df], axis=1)

In [6]:
df

,monomer,SMILES,class,type,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,MolWt,...,fr_C_O_noCOO,fr_NH0,fr_NH1,fr_NH2,fr_amide,fr_benzene,fr_guanido,fr_imidazole,fr_para_hydroxylation,fr_unbrch_alkane
0,G,C(C(=O)O)N,peptide,node,9.243056,9.243056,0.277778,-0.967593,0.421171,75.067,...,0,0,0,1,0,0,0,0,0,0
1,A,C[C@@H](C(=O)O)N,peptide,node,9.574074,9.574074,0.731481,-0.962963,0.451352,89.094,...,0,0,0,1,0,0,0,0,0,0
2,L,CC(C)C[C@@H](C(=O)O)N,peptide,node,10.109769,10.109769,0.357500,-0.913241,0.583947,131.175,...,0,0,0,1,0,0,0,0,0,0
3,M,CSCC[C@@H](C(=O)O)N,peptide,node,10.070883,10.070883,0.552083,-0.912917,0.596996,149.215,...,0,0,0,1,0,0,0,0,0,0
4,F,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,peptide,node,10.378642,10.378642,0.385093,-0.959395,0.690463,165.192,...,0,0,0,1,0,1,0,0,0,0
5,W,C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N,peptide,node,10.626394,10.626394,0.346574,-0.971962,0.700584,204.229,...,0,0,1,1,0,1,0,0,1,0
6,K,C(CCN)C[C@@H](C(=O)O)N,peptide,node,10.137222,10.137222,0.520370,-0.933313,0.457177,146.190,...,0,0,0,2,0,0,0,0,0,1
7,Q,C(CC(=O)N)[C@@H](C(=O)O)N,peptide,node,10.100084,10.100084,0.021296,-1.109954,0.456092,146.146,...,1,0,0,2,1,0,0,0,0,0
8,E,C(CC(=O)O)[C@@H](C(=O)O)N,peptide,node,9.993880,9.993880,0.023148,-1.165509,0.485976,147.130,...,0,0,0,1,0,0,0,0,0,0
9,S,C([C@@H](C(=O)O)N)O,peptide,node,9.645324,9.645324,0.504630,-1.178241,0.394240,105.093,...,0,0,0,1,0,0,0,0,0,0
10,P,C1C[C@H](NC1)C(=O)O,peptide,node,10.139074,10.139074,0.268519,-0.719907,0.498209,115.132,...,0,0,1,0,0,0,0,0,0,0
11,V,CC(C)[C@@H](C(=O)O)N,peptide,node,10.015741,10.015741,0.020833,-0.930556,0.536977,117.148,...,0,0,0,1,0,0,0,0,0,0
12,I,CC[C@H](C)[C@@H](C(=O)O)N,peptide,node,10.174630,10.174630,0.071759,-0.912639,0.583947,131.175,...,0,0,0,1,0,0,0,0,0,0
13,C,C([C@@H](C(=O)O)N)S,peptide,node,9.756435,9.756435,0.189815,-1.004630,0.424382,121.161,...,0,0,0,1,0,0,0,0,0,0
14,Y,C1=CC(=CC=C1C[C@@H](C(=O)O)N)O,peptide,node,10.396196,10.396196,0.159858,-1.020301,0.627720,181.191,...,0,0,0,1,0,1,0,0,0,0
15,H,C1=C(NC=N1)C[C@@H](C(=O)O)N,peptide,node,10.266220,10.266220,0.287037,-1.000370,0.541194,155.157,...,0,1,1,1,0,0,0,1,0,0
16,R,C(C[C@@H](C(=O)O)N)CN=C(N)N,peptide,node,10.217142,10.217142,0.012867,-1.000278,0.227783,174.204,...,0,1,0,3,0,0,1,0,0,0
17,N,C([C@@H](C(=O)O)N)C(=O)N,peptide,node,9.993056,9.993056,0.310185,-1.214074,0.423939,132.119,...,1,0,0,2,1,0,0,0,0,0
18,D,C([C@@H](C(=O)O)N)C(=O)O,peptide,node,9.846435,9.846435,0.532407,-1.294074,0.452021,133.103,...,0,0,0,1,0,0,0,0,0,0
19,T,C[C@H]([C@@H](C(=O)O)N)O,peptide,node,9.855741,9.855741,0.979167,-1.180556,0.425096,119.120,...,0,0,0,1,0,0,0,0,0,0
20,G_amd,C(C(=O)N)N,peptide_amd,node,9.465278,9.465278,0.055556,-0.467593,0.394253,74.083,...,1,0,0,2,1,0,0,0,0,0
21,A_amd,C[C@@H](C(=O)N)N,peptide_amd,node,9.796296,9.796296,0.462963,-0.509259,0.423257,88.110,...,1,0,0,2,1,0,0,0,0,0
22,L_amd,CC(C)C[C@@H](C(=O)N)N,peptide_amd,node,10.331991,10.331991,0.413241,-0.467593,0.557252,130.191,...,1,0,0,2,1,0,0,0,0,0
23,M_amd,CSCC[C@@H](C(=O)N)N,peptide_amd,node,10.293106,10.293106,0.412917,-0.460694,0.567182,148.231,...,1,0,0,2,1,0,0,0,0,0
24,F_amd,C1=CC=C(C=C1)C[C@@H](C(=O)N)N,peptide_amd,node,10.600864,10.600864,0.459395,-0.576481,0.661945,164.208,...,1,0,0,2,1,1,0,0,0,0
25,W_amd,C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)N)N,peptide_amd,node,10.848616,10.848616,0.471574,-0.621105,0.679094,203.245,...,1,0,1,2,1,1,0,0,1,0
26,K_amd,C(CCN)C[C@@H](C(=O)N)N,peptide_amd,node,10.359444,10.359444,0.433313,-0.493935,0.429639,145.206,...,1,0,0,3,1,0,0,0,0,1
27,Q_amd,C(CC(=O)N)[C@@H](C(=O)N)N,peptide_amd,node,10.256919,10.256919,0.101296,-0.756944,0.427569,145.162,...,2,0,0,3,2,0,0,0,0,0
28,E_amd,C(CC(=O)O)[C@@H](C(=O)N)N,peptide_amd,node,10.216103,10.216103,0.101852,-0.975278,0.456092,146.146,...,1,0,0,2,1,0,0,0,0,0
29,S_amd,C([C@@H](C(=O)N)N)O,peptide_amd,node,9.867546,9.867546,0.379630,-0.902778,0.370821,104.109,...,1,0,0,2,1,0,0,0,0,0
30,P_amd,C1C[C@H](NC1)C(=O)N,peptide_amd,node,10.361296,10.361296,0.046296,-0.219907,0.469740,114.148,...,1,0,1,1,1,0,0,0,0,0
31,V_amd,CC(C)[C@@H](C(=O)N)N,peptide_amd,node,10.237963,10.237963,0.145833,-0.490741,0.508157,116.164,...,1,0,0,2,1,0,0,0,0,0
32,I_amd,CC[C@H](C)[C@@H](C(=O)N)N,peptide_amd,node,10.396852,10.396852,0.196759,-0.476852,0.557252,130.191,...,1,0,0,2,1,0,0,0,0,0
33,C_amd,C([C@@H](C(=O)N)N)S,peptide_amd,node,9.978657,9.978657,0.314815,-0.594136,0.397566,120.177,...,1,0,0,2,1,0,0,0,0,0
34,Y_amd,C1=CC(=CC=C1C[C@@H](C(=O)N)N)O,peptide_amd,node,10.618418,10.618418,0.191108,-0.662460,0.598665,180.207,...,1,0,0,2,1,1,0,0,0,0
35,H_amd,C1=C(NC=N1)C[C@@H](C(=O)N)N,peptide_amd,node,10.488442,10.488442,0.412037,-0.629213,0.507774,154.173,...,1,1,1,2,1,0,0,1,0,0
36,R_amd,C(C[C@@H](C(=O)N)N)CN=C(N)N,peptide_amd,node,10.439364,10.439364,0.044117,-0.597964,0.214102,173.220,...,1,1,0,4,1,0,1,0,0,0
37,N_amd,C([C@@H](C(=O)N)N)C(=O)N,peptide_amd,node,10.124213,10.124213,0.185185,-0.942130,0.399063,131.135,...,2,0,0,3,2,0,0,0,0,0
38,D_amd,C([C@@H](C(=O)N)N)C(=O)O,peptide_amd,node,10.068657,10.068657,0.407407,-1.123796,0.423939,132.119,...,1,0,0,2,1,0,0,0,0,0
39,T_amd,C[C@H]([C@@H](C(=O)N)N)O,peptide_amd,node,10.077963,10.077963,0.680556,-0.935185,0.398532,118.136,...,1,0,0,2,1,0,0,0,0,0
40,Tma,C[N+](C)(C)CCCNC(=O)C=C,polymer,node,10.702037,10.702037,0.086658,-0.086658,0.361624,171.264,...,1,1,1,0,1,0,0,0,0,0
41,Aeg,NC(=[NH2+])NCCNC(=O)C=C,polymer,node,10.530232,10.530232,0.150789,-0.206118,0.151122,157.197,...,1,0,2,2,1,0,1,0,0,0
42,Mo,C=CC(=O)N1CCOCC1,polymer,node,10.919167,10.919167,0.003056,0.003056,0.482094,141.170,...,1,1,0,0,1,0,0,0,0,0
43,Mep,COCCCNC(=O)C=C,polymer,node,10.504970,10.504970,0.128608,-0.128608,0.444504,143.186,...,1,0,1,0,1,0,0,0,0,0
44,Ni,CC(C)NC(=O)C=C,polymer,node,10.393056,10.393056,0.111111,-0.111111,0.524524,113.160,...,1,0,1,0,1,0,0,0,0,0
45,Phe,C=CC(=O)Nc1ccccc1,polymer,node,10.752041,10.752041,0.184074,-0.184074,0.634893,147.177,...,1,0,1,0,1,1,0,0,1,0
46,Do,CCCCCCCCCCCCNC(=O)C=C,polymer,node,10.842977,10.842977,0.054700,-0.054700,0.400991,239.403,...,1,0,1,0,1,0,0,0,0,9
47,Bam,CCCCNC(=O)C=C,polymer,node,10.457457,10.457457,0.080139,-0.080139,0.444229,127.187,...,1,0,1,0,1,0,0,0,0,1
48,Oct,CCCCCCCCNC(=O)C=C,polymer,node,10.717823,10.717823,0.061520,-0.061520,0.454680,183.295,...,1,0,1,0,1,0,0,0,0,5
49,Olam,CCCCCCCC/C=C\CCCCCCCCNC(=O)C(=C),polymer,node,10.936583,10.936583,0.057642,-0.057642,0.189297,321.549,...,1,0,1,0,1,0,0,0,0,12
50,Bmam,CCCCOCNC(=O)C=C,polymer,node,10.535327,10.535327,0.193057,-0.193057,0.355510,157.213,...,1,0,1,0,1,0,0,0,0,1
51,Tmb,CC(C)(C)CC(C)(C)NC(=O)C=C,polymer,node,11.084109,11.084109,0.102546,-0.163171,0.669160,183.295,...,1,0,1,0,1,0,0,0,0,0
52,AMB,CNC(C)=O,peptide,edge,9.701389,9.701389,0.004630,0.004630,0.420717,73.095,...,1,0,1,0,1,0,0,0,0,0
53,CC,CC,polymer,edge,2.000000,2.000000,2.000000,2.000000,0.372786,30.070,...,0,0,0,0,0,0,0,0,0,0

## Analyze Features

### Ensure each class has >1

In [7]:
def get_unique(X):
    """
        returns: unique descriptors, homogenous descriptors
    """
    X = X.apply(set, axis=0).map(len)
    return set(X[X>1].index.tolist())

In [8]:
descriptors = df.select_dtypes(include='number').columns.tolist()

In [9]:
# Verify
# set([desc.lower() for desc in descriptors]) == set(allowed_descriptors)

### Node Descriptors:

In [10]:
unique_descriptors_peptide = get_unique(df[(df['type'] == 'node') & (df['class'] == 'peptide')][descriptors])
unique_descriptors_peptide_amd = get_unique(df[(df['type'] == 'node') & (df['class'] == 'peptide_amd')][descriptors])
unique_descriptors_polymer = get_unique(df[(df['type'] == 'node') & (df['class'] == 'polymer')][descriptors])
node_descriptors = list(unique_descriptors_peptide & unique_descriptors_peptide_amd & unique_descriptors_polymer)

### Edge Descriptors:

In [11]:
edge_descriptors = list(get_unique(df[df['type'] == 'edge'][descriptors]))

## Export to .json

In [12]:
df[df['type'] == 'node'][sum([['monomer', 'SMILES', 'class', 'type'], node_descriptors],[])].to_csv('node_feats.csv', index=False)
df[df['type'] == 'edge'][sum([['monomer', 'SMILES', 'class', 'type'], edge_descriptors],[])].to_csv('edge_feats.csv', index=False)

In [13]:
json_data = pd.DataFrame({'node': [node_descriptors], 'edge': [edge_descriptors]})

In [14]:
json_data.to_json('../unique_descriptors.json', orient='records')

In [15]:
pd.read_json('../unique_descriptors.json').to_dict(orient='records')[0]

{'node': ['qed',
  'NumHeteroatoms',
  'EState_VSA5',
  'BCUT2D_CHGHI',
  'VSA_EState6',
  'Chi4n',
  'VSA_EState5',
  'FpDensityMorgan3',
  'Chi1v',
  'HallKierAlpha',
  'NumRotatableBonds',
  'PEOE_VSA7',
  'EState_VSA4',
  'BCUT2D_CHGLO',
  'Chi1n',
  'fr_unbrch_alkane',
  'EState_VSA9',
  'NumHAcceptors',
  'NumSaturatedHeterocycles',
  'HeavyAtomCount',
  'VSA_EState7',
  'SMR_VSA6',
  'SlogP_VSA4',
  'fr_NH0',
  'MinPartialCharge',
  'NumHDonors',
  'EState_VSA3',
  'Chi3v',
  'TPSA',
  'SMR_VSA7',
  'MaxPartialCharge',
  'PEOE_VSA9',
  'BertzCT',
  'fr_guanido',
  'Chi4v',
  'MaxAbsPartialCharge',
  'MolLogP',
  'SMR_VSA4',
  'PEOE_VSA1',
  'Kappa2',
  'MinEStateIndex',
  'VSA_EState8',
  'Chi0n',
  'SMR_VSA5',
  'fr_para_hydroxylation',
  'EState_VSA2',
  'LabuteASA',
  'ExactMolWt',
  'NumAromaticRings',
  'Chi1',
  'SlogP_VSA1',
  'BCUT2D_LOGPHI',
  'fr_NH1',
  'SMR_VSA1',
  'Chi3n',
  'MaxAbsEStateIndex',
  'SMR_VSA10',
  'EState_VSA6',
  'NOCount',
  'MolWt',
  'Chi2n',
  'NumAromaticCarbocycles',
  'NumValenceElectrons',
  'VSA_EState3',
  'SlogP_VSA3',
  'SMR_VSA3',
  'MinAbsEStateIndex',
  'SlogP_VSA5',
  'NHOHCount',
  'RingCount',
  'fr_benzene',
  'NumSaturatedRings',
  'Kappa1',
  'BCUT2D_MWHI',
  'FpDensityMorgan1',
  'VSA_EState4',
  'NumAliphaticRings',
  'BalabanJ',
  'MaxEStateIndex',
  'Chi0',
  'SlogP_VSA6',
  'EState_VSA8',
  'FpDensityMorgan2',
  'BCUT2D_MRLOW',
  'MinAbsPartialCharge',
  'PEOE_VSA6',
  'FractionCSP3',
  'PEOE_VSA2',
  'Kappa3',
  'VSA_EState2',
  'NumAliphaticHeterocycles',
  'fr_NH2',
  'PEOE_VSA14',
  'MolMR',
  'HeavyAtomMolWt',
  'PEOE_VSA8',
  'Chi2v',
  'EState_VSA7',
  'BCUT2D_LOGPLOW',
  'Chi0v',
  'SlogP_VSA2',
  'BCUT2D_MRHI',
  'BCUT2D_MWLOW',
  'PEOE_VSA10'],
 'edge': ['qed',
  'NumHeteroatoms',
  'EState_VSA5',
  'BCUT2D_CHGHI',
  'VSA_EState5',
  'FpDensityMorgan3',
  'Chi1v',
  'HallKierAlpha',
  'BCUT2D_CHGLO',
  'Chi1n',
  'NumHAcceptors',
  'HeavyAtomCount',
  'SMR_VSA6',
  'MinPartialCharge',
  'NumHDonors',
  'Chi3v',
  'TPSA',
  'MaxPartialCharge',
  'BertzCT',
  'MaxAbsPartialCharge',
  'MolLogP',
  'PEOE_VSA1',
  'Kappa2',
  'MinEStateIndex',
  'VSA_EState8',
  'Chi0n',
  'SMR_VSA5',
  'EState_VSA2',
  'LabuteASA',
  'ExactMolWt',
  'Chi1',
  'fr_C_O',
  'SlogP_VSA1',
  'BCUT2D_LOGPHI',
  'fr_NH1',
  'SMR_VSA1',
  'Chi3n',
  'MaxAbsEStateIndex',
  'SMR_VSA10',
  'EState_VSA6',
  'NOCount',
  'PEOE_VSA12',
  'MolWt',
  'Chi2n',
  'NumValenceElectrons',
  'VSA_EState3',
  'SlogP_VSA3',
  'SMR_VSA3',
  'EState_VSA10',
  'MinAbsEStateIndex',
  'fr_C_O_noCOO',
  'SlogP_VSA5',
  'NHOHCount',
  'Kappa1',
  'BCUT2D_MWHI',
  'FpDensityMorgan1',
  'BalabanJ',
  'MaxEStateIndex',
  'Chi0',
  'fr_amide',
  'EState_VSA8',
  'FpDensityMorgan2',
  'BCUT2D_MRLOW',
  'MinAbsPartialCharge',
  'PEOE_VSA6',
  'FractionCSP3',
  'PEOE_VSA2',
  'Kappa3',
  'VSA_EState2',
  'MolMR',
  'HeavyAtomMolWt',
  'PEOE_VSA8',
  'Chi2v',
  'EState_VSA7',
  'BCUT2D_LOGPLOW',
  'Chi0v',
  'SlogP_VSA2',
  'BCUT2D_MRHI',
  'BCUT2D_MWLOW']}

## Scaling / Normalization:

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import QuantileTransformer

In [ ]:
original_data = new_df['vsa_estate3']

# Box-Cox
# scaled_data = stats.zscore(original_data)
# scaled_data = scaled_data + abs(scaled_data.min()) + 0.01
# normalized_data = stats.boxcox(scaled_data)

# Yeo-Johnson
# scaled_data = stats.zscore(original_data)
# normalized_data = stats.yeojohnson(scaled_data)

# Quantile Transformer
# quantile = QuantileTransformer(output_distribution='normal', n_quantiles = 52)
# normalized_data = quantile.fit_transform(np.array(original_data).reshape(-1, 1))

In [ ]:
original_data = new_df['chi1']
quantile = QuantileTransformer(output_distribution='normal', n_quantiles = 52)
normalized_data = quantile.fit_transform(np.array(original_data).reshape(-1, 1))

fig, ax=plt.subplots(1, 3, figsize=(15, 3))
sns.histplot(original_data, ax=ax[0], kde=True, legend=False)
ax[0].set_title("Original Data")
sns.histplot(scaled_data, ax=ax[1], kde=True, legend=False)
ax[1].set_title("Scaled Data")
sns.histplot(normalized_data, ax=ax[2], kde=True, legend=False)
ax[2].set_title("Normalized data")
plt.show()

In [ ]:
from scipy.stats import shapiro
shapiro(normalized_data)

In [ ]:
# Of the descriptors, compute the nonzero percent for classes 'peptide', 'polymer'; 
# divide min / max and see if > threshold %